apiVersion: v2
name: cassandra
description: A Helm chart for Apache Cassandra with authentication and PVC storage
type: application
version: 0.1.1
appVersion: "4.1.4"
keywords:
  - database
  - nosql
  - cassandra
home: https://cassandra.apache.org/
sources:
  - https://github.com/apache/cassandra
maintainers:
  - name: DevOps Engineer
    email: devops@example.com