# Default values for cassandra

image:
  repository: cassandra
  tag: "4.1.4"
  pullPolicy: IfNotPresent

# Cluster configuration
cluster:
  name: "cassandra-cluster"
  dc: "dc1"
  rack: "rack1"

# Resource limits
resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

# Authentication settings
auth:
  enabled: true
  superuser:
    username: "cassandra"
    password: "changeme123"

# Persistence configuration
persistence:
  enabled: true
  storageClass: ""  # Use default storage class
  size: 10Gi
  accessMode: ReadWriteOnce

# Service configuration  
service:
  type: ClusterIP
  cqlPort: 9042
  jmxPort: 7199

# JVM Settings
jvm:
  heapSize: "1G"
  
# Node count
replicaCount: 1

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}