apiVersion: v1
kind: Service
metadata:
  name: {{ include "cassandra.fullname" . }}
  labels:
    {{- include "cassandra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.cqlPort }}
      targetPort: cql
      protocol: TCP
      name: cql
    - port: {{ .Values.service.jmxPort }}
      targetPort: jmx
      protocol: TCP
      name: jmx
  selector:
    {{- include "cassandra.selectorLabels" . | nindent 4 }}