name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout full history (needed for tags)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Configure Git
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # 3️⃣ Create a version tag if none exists for this commit
      - name: Create version tag
        id: tag
        run: |
          # Get latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"

          # Increment patch version
          IFS='.' read -r MAJOR MINOR PATCH <<< "${LATEST_TAG#v}"
          PATCH=$((PATCH+1))
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"

          echo "New tag: $NEW_TAG"
          git tag $NEW_TAG
          git push origin $NEW_TAG
          echo "TAG=$NEW_TAG" >> $GITHUB_ENV

      # 4️⃣ Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.13.0'

      # 5️⃣ Run chart-releaser
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
          skip_existing: true
          pages_branch: gh-pages
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
